import { NextRequest, NextResponse } from 'next/server';
import { runWoningScraper } from '@/lib/apify';
import { SearchFilters, SearchResponse, ApifyRunInput } from '@/types';

export async function POST(request: NextRequest) {
  try {
    const body: SearchFilters = await request.json();

    if (!body.locatie) {
      return NextResponse.json<SearchResponse>(
        { success: false, error: 'Locatie is verplicht' },
        { status: 400 }
      );
    }

    const apifyInput: ApifyRunInput = {
      location: body.locatie,
      propertyType: body.type,
      minPrice: body.minPrijs ? parseInt(body.minPrijs) : undefined,
      maxPrice: body.maxPrijs ? parseInt(body.maxPrijs) : undefined,
      minRooms: body.kamers ? parseInt(body.kamers.replace('+', '')) : undefined,
      houseType: body.woningType || undefined,
    };

    // Always return mock data for demo/testing
    const mockData = getMockData(body.locatie);
    return NextResponse.json<SearchResponse>({
      success: true,
      data: mockData,
      totalResults: mockData.length,
    });
  } catch (error) {
    console.error('Search API error:', error);

    // Return mock data for development
    if (process.env.NODE_ENV === 'development') {
      const mockData = getMockData(body.locatie || 'Amsterdam');
      return NextResponse.json<SearchResponse>({
        success: true,
        data: mockData,
        totalResults: mockData.length,
      });
    }

    return NextResponse.json<SearchResponse>(
      { success: false, error: 'Er is een fout opgetreden bij het zoeken' },
      { status: 500 }
    );
  }
}

function getMockData(location: string) {
  const locationLower = location.toLowerCase();

  // Amsterdam mock data
  if (locationLower.includes('amsterdam')) {
    return [
      {
        id: 'ams-1',
        titel: 'Luxe grachtenpand appartement',
        adres: 'Herengracht 256',
        postcode: '1016 BV',
        plaats: 'Amsterdam',
        prijs: 595000,
        kamers: 3,
        oppervlakte: 95,
        foto: 'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&h=600&fit=crop',
        type: 'Appartement',
        url: 'https://funda.nl',
        makelaar: 'Amsterdam Grachtenmakelaars',
        energielabel: 'A',
      },
      {
        id: 'ams-2',
        titel: 'Modern appartement De Pijp',
        adres: 'Ferdinand Bolstraat 78',
        postcode: '1072 LM',
        plaats: 'Amsterdam',
        prijs: 425000,
        kamers: 2,
        oppervlakte: 65,
        foto: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop',
        type: 'Appartement',
        url: 'https://funda.nl',
        makelaar: 'De Pijp Makelaars',
        energielabel: 'B',
      },
      {
        id: 'ams-3',
        titel: 'Penthouse met dakterras Zuidas',
        adres: 'Gustav Mahlerlaan 10',
        postcode: '1082 PP',
        plaats: 'Amsterdam',
        prijs: 1250000,
        kamers: 4,
        oppervlakte: 145,
        foto: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop',
        type: 'Penthouse',
        url: 'https://funda.nl',
        makelaar: 'Zuidas Luxury Real Estate',
        energielabel: 'A++',
      },
      {
        id: 'ams-4',
        titel: 'Karakteristiek bovenhuis Jordaan',
        adres: 'Bloemgracht 42',
        postcode: '1015 TM',
        plaats: 'Amsterdam',
        prijs: 485000,
        kamers: 2,
        oppervlakte: 75,
        foto: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&h=600&fit=crop',
        type: 'Bovenwoning',
        url: 'https://funda.nl',
        makelaar: 'Jordaan Woningen',
        energielabel: 'C',
      },
      {
        id: 'ams-5',
        titel: 'Ruim familie appartement Oost',
        adres: 'Linnaeusstraat 89',
        postcode: '1093 EK',
        plaats: 'Amsterdam',
        prijs: 550000,
        kamers: 4,
        oppervlakte: 110,
        foto: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop',
        type: 'Appartement',
        url: 'https://funda.nl',
        makelaar: 'Oost Amsterdam Makelaardij',
        energielabel: 'A',
      },
      {
        id: 'ams-6',
        titel: 'Cozy studio centrum',
        adres: 'Spuistraat 150',
        postcode: '1012 VT',
        plaats: 'Amsterdam',
        prijs: 245000,
        kamers: 1,
        oppervlakte: 32,
        foto: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop',
        type: 'Studio',
        url: 'https://funda.nl',
        makelaar: 'City Center Makelaars',
        energielabel: 'B',
      },
      {
        id: 'ams-7',
        titel: 'Nieuwbouw loft NDSM-werf',
        adres: 'NDSM-Plein 28',
        postcode: '1033 WB',
        plaats: 'Amsterdam',
        prijs: 675000,
        kamers: 3,
        oppervlakte: 120,
        foto: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
        type: 'Loft',
        url: 'https://funda.nl',
        makelaar: 'Noord Amsterdam Vastgoed',
        energielabel: 'A+',
      },
      {
        id: 'ams-8',
        titel: 'Gerenoveerd appartement Rivierenbuurt',
        adres: 'Churchilllaan 65',
        postcode: '1078 DL',
        plaats: 'Amsterdam',
        prijs: 395000,
        kamers: 2,
        oppervlakte: 70,
        foto: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&h=600&fit=crop',
        type: 'Appartement',
        url: 'https://funda.nl',
        makelaar: 'Zuid Makelaardij',
        energielabel: 'B',
      },
    ];
  }

  // Rotterdam mock data
  if (locationLower.includes('rotterdam')) {
    return [
      {
        id: 'rtd-1',
        titel: 'Skyline appartement Kop van Zuid',
        adres: 'Wilhelminakade 123',
        postcode: '3072 AP',
        plaats: 'Rotterdam',
        prijs: 485000,
        kamers: 3,
        oppervlakte: 95,
        foto: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop',
        type: 'Appartement',
        url: 'https://funda.nl',
        makelaar: 'Rotterdam Skyline Makelaars',
        energielabel: 'A',
      },
      {
        id: 'rtd-2',
        titel: 'Herenhuis Kralingen',
        adres: 'Kralingse Plaslaan 45',
        postcode: '3062 DB',
        plaats: 'Rotterdam',
        prijs: 795000,
        kamers: 5,
        oppervlakte: 165,
        foto: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=600&fit=crop',
        type: 'Herenhuis',
        url: 'https://funda.nl',
        makelaar: 'Kralingen Vastgoed',
        energielabel: 'B',
      },
      {
        id: 'rtd-3',
        titel: 'Loft in oude havenloods',
        adres: 'Lloydstraat 88',
        postcode: '3024 EA',
        plaats: 'Rotterdam',
        prijs: 425000,
        kamers: 2,
        oppervlakte: 110,
        foto: 'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&h=600&fit=crop',
        type: 'Loft',
        url: 'https://funda.nl',
        makelaar: 'Haven Rotterdam Makelaars',
        energielabel: 'C',
      },
      {
        id: 'rtd-4',
        titel: 'Modern appartement Markthal',
        adres: 'Dominee Jan Scharpstraat 12',
        postcode: '3011 GZ',
        plaats: 'Rotterdam',
        prijs: 375000,
        kamers: 2,
        oppervlakte: 72,
        foto: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop',
        type: 'Appartement',
        url: 'https://funda.nl',
        makelaar: 'Centrum Rotterdam',
        energielabel: 'A',
      },
      {
        id: 'rtd-5',
        titel: 'Penthouse De Rotterdam toren',
        adres: 'Wilhelminakade 179',
        postcode: '3072 AP',
        plaats: 'Rotterdam',
        prijs: 1450000,
        kamers: 4,
        oppervlakte: 180,
        foto: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop',
        type: 'Penthouse',
        url: 'https://funda.nl',
        makelaar: 'Luxury Rotterdam Living',
        energielabel: 'A++',
      },
      {
        id: 'rtd-6',
        titel: 'Starter appartement Noord',
        adres: 'Bergselaan 234',
        postcode: '3037 CC',
        plaats: 'Rotterdam',
        prijs: 225000,
        kamers: 2,
        oppervlakte: 55,
        foto: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop',
        type: 'Appartement',
        url: 'https://funda.nl',
        makelaar: 'Rotterdam Noord Makelaars',
        energielabel: 'C',
      },
      {
        id: 'rtd-7',
        titel: 'Gezinswoning Hillegersberg',
        adres: 'Straatweg 156',
        postcode: '3054 AM',
        plaats: 'Rotterdam',
        prijs: 595000,
        kamers: 4,
        oppervlakte: 135,
        foto: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop',
        type: 'Eengezinswoning',
        url: 'https://funda.nl',
        makelaar: 'Hillegersberg Woningen',
        energielabel: 'B',
      },
      {
        id: 'rtd-8',
        titel: 'Studio bij Erasmusbrug',
        adres: 'Boompjes 60',
        postcode: '3011 XB',
        plaats: 'Rotterdam',
        prijs: 195000,
        kamers: 1,
        oppervlakte: 38,
        foto: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
        type: 'Studio',
        url: 'https://funda.nl',
        makelaar: 'Waterfront Makelaardij',
        energielabel: 'B',
      },
    ];
  }

  // Default mock data for other locations
  return [
    {
      id: '1',
      titel: 'Prachtig appartement in centrum',
      adres: 'Hoofdstraat 123',
      postcode: '1000 AA',
      plaats: location,
      prijs: 425000,
      kamers: 3,
      oppervlakte: 85,
      foto: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop',
      type: 'Appartement',
      url: 'https://funda.nl',
      makelaar: 'Lokale Makelaardij',
      energielabel: 'A',
    },
    {
      id: '2',
      titel: 'Ruime gezinswoning met tuin',
      adres: 'Parkstraat 45',
      postcode: '1000 BB',
      plaats: location,
      prijs: 550000,
      kamers: 5,
      oppervlakte: 140,
      foto: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=600&fit=crop',
      type: 'Eengezinswoning',
      url: 'https://funda.nl',
      makelaar: 'Makelaars Groep',
      energielabel: 'B',
    },
    {
      id: '3',
      titel: 'Moderne nieuwbouwwoning',
      adres: 'Nieuwbouwlaan 78',
      postcode: '1000 CC',
      plaats: location,
      prijs: 389000,
      kamers: 4,
      oppervlakte: 110,
      foto: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop',
      type: '2-onder-1-kap',
      url: 'https://funda.nl',
      makelaar: 'Vastgoed Plus',
      energielabel: 'A++',
    },
    {
      id: '4',
      titel: 'Karakteristiek herenhuis',
      adres: 'Grachtweg 12',
      postcode: '1000 DD',
      plaats: location,
      prijs: 675000,
      kamers: 6,
      oppervlakte: 180,
      foto: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&h=600&fit=crop',
      type: 'Herenhuis',
      url: 'https://funda.nl',
      makelaar: 'Premium Woningen',
      energielabel: 'C',
    },
    {
      id: '5',
      titel: 'Luxe penthouse met uitzicht',
      adres: 'Torenplein 42',
      postcode: '1000 EE',
      plaats: location,
      prijs: 895000,
      kamers: 4,
      oppervlakte: 150,
      foto: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop',
      type: 'Penthouse',
      url: 'https://funda.nl',
      makelaar: 'Luxury Living',
      energielabel: 'A+',
    },
    {
      id: '6',
      titel: 'Gezellige studio in de stad',
      adres: 'Stationsweg 8',
      postcode: '1000 FF',
      plaats: location,
      prijs: 189000,
      kamers: 1,
      oppervlakte: 35,
      foto: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop',
      type: 'Studio',
      url: 'https://funda.nl',
      makelaar: 'City Makelaars',
      energielabel: 'B',
    },
    {
      id: '7',
      titel: 'Sfeervolle hoekwoning',
      adres: 'Laanstraat 56',
      postcode: '1000 GG',
      plaats: location,
      prijs: 445000,
      kamers: 4,
      oppervlakte: 125,
      foto: 'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&h=600&fit=crop',
      type: 'Hoekwoning',
      url: 'https://funda.nl',
      makelaar: 'Wonen & Meer',
      energielabel: 'B',
    },
    {
      id: '8',
      titel: 'Licht appartement met balkon',
      adres: 'Zonnelaan 90',
      postcode: '1000 HH',
      plaats: location,
      prijs: 325000,
      kamers: 2,
      oppervlakte: 68,
      foto: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop',
      type: 'Appartement',
      url: 'https://funda.nl',
      makelaar: 'Stad & Land Makelaars',
      energielabel: 'A',
    },
  ];
}
